### ISSUE TITLE
List of features for preview release

### ISSUE THREAD

**Issue by wateret** [wateret/mengde#128]
So far the development of "mengde" had no milestones for release. not organized well. When I came up with something, then just implemented that. However it is about time for thinking about what we need for release.

### Mandatory

- [x] Write `docs/Introduction.md` #126 
- [x] Implement more EventEffects #103 
- [x] Implement more Magic effects #104
- [x] Implement more lua API #132
- [x] Support various types of enemy AI which can be set by script #131
- [x] Basic keyboard support #130
- [x] Support save files #17
- [ ] Update example scenario so it can show most of the game features
- [ ] Graphical resources for example scenario 😭#133
- [ ] Better error handling on configuration import #14
- [ ] Error handling of lua scripts
- [x] Sandboxing Lua scripts #138 
- [ ] [gui] Refine User Interface
    - [ ] In-game menu
- [ ] Fix memory leak

### Optional

- Global configuration
- Heroes' feature #91 
- Build on Windows #13
